[package]
name = "spritzer"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.20"
assembly = { path = "../assembly" }
common = { path = "../common" }
strum = "0.26.1"
strum_macros = "0.26.1"
rand = "0.8.5"
getrandom = { version = "0.2", features = ["js"] }
simplelog = {version = "^0.12.1", features = ["paris"], optional = true}
binary-reader = "0.4.5"

[features]
build-binary = ["simplelog"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "spritzer"
crate-type = ["lib"]
path = "lib.rs"

[[bin]]
name = "debug"
path = "debug.rs"
required-features = ["build-binary"]
