[package]
edition = "2021"
name = "common"
version = "0.1.0"

[dependencies]
log = "0.4.20"
strum = "0.26.1"
strum_macros = "0.26.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["lib"]
name = "common"
path = "lib.rs"
