on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v3
    - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Set env
    - uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - run: pip install -r src/requirements.txt pyinstaller
    - run: pyinstaller src/main.py -F -n=spritzer-{{ env.RELEASE_VERSION }} # Package CLI
    - uses: actions/upload-artifact@v2
      with:
        path: dist/*
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/*
